### ISSUE TITLE
I find an ERROR

### ISSUE THREAD

**Issue by samupereyra7** [GeorgiKeranov/facebook-marketplace-bot#1]
ERROR: Timed out waiting for the element with css selector "a[href="/marketplace/you/selling/"]:not([aria-current="page"])" to load

**Comment by GeorgiKeranov** [comment]
Hello, thank you for the issue. I have changed the selector for the "Your Listings" button and now it works correctly! If you still have an error, please open the issue and write what kind of error do you get.
