### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by mercuryin** [GeorgiKeranov/facebook-marketplace-bot#13]
Hello, I have everything installed and configured but when I type python3 main.py it opens a new Chrome window, I do accept cookies, log in and open facebook and nothing happen. If I run the command again it ask again for the log in credentials all the time.

**Comment by MasonCable** [comment]
I am having the same issue, the script it able to fill out some fields, but not others. I've only been tinkering for an hour or so, but when I figure out the solution I will let you know.

Edit: I was able to fix the application for the most part, Facebook changed a lot of their HTML values to prevent bots, but with some workaround I was able to get things working again, there is a fork that you can use located on my page along with a new testing csv file.

**Comment by GeorgiKeranov** [comment]
@mercuryin do you get any errors in the console and can you paste them here?

@MasonCable Thanks for the update, I would test it and add it to `master` if it works!

**Comment by F-UwU-aaa** [comment]
Alguien sabe si sigue funcionando o tiene algún error el programa gracias :3 @GeorgiKeranov

**Comment by MasonCable** [comment]
@Jhoel-chipana-paye-FIRU  Certain aspects of the code work and other don't due to Facebook, you'll have to do some manual work or talk to someone in order to get specific use cases resolved.

**Comment by F-UwU-aaa** [comment]
@MasonCable que mal y supieras como puedo arreglar o con quién puedo hablar si o contigo pueblo hablar por que nose mucho de código :"""" x fa o algún canal de Youtube x fa manito :3

**Comment by MasonCable** [comment]
@Jhoel-chipana-paye-FIRU 

When you use my fork, what errors are you running into? Also, if you don't know how to write code then this is going to be pretty difficult to get working on your end. If I have some free time I will try and get things worked out. If and when I do, I will push up a branch and link it to you.

**Comment by john123131** [comment]
We need to figure out a way to bypass their bot detection with this script. At around high volumes of 50-60 listings per day, each facebook marketplace account I use gets banned.

**Comment by GeorgiKeranov** [comment]
> We need to figure out how to bypass their bot detection with this script. At around high volumes of 50-60 listings per day, each Facebook marketplace account I use gets banned.

@john123131 

The script shouldn't be detected because it would get you banned after the 1st listing. I think that your account gets banned because you are using it too frequently. For example, I use it every week once to renew my listings.

**Comment by john123131** [comment]
Right, we need to figure out how to have it not get banned from using it everyday. Once per week does not work for my use case.

**Comment by GeorgiKeranov** [comment]
@john123131 

> Right, we need to figure out how to have it not get banned from using it everyday. Once per week does not work for my use case.

I am sure that if you do it without the script, manually every day you will get banned again and this is not coming from the script but from the too frequent deletes and uploads of listings so we can do nothing these are the facebook internal rules.

**Comment by akosgoncz** [comment]
Hello.

I get this error: ERROR: Timed out waiting for the element with xpath "//span[@dir="auto"][text()="Used – Good"]" to load

Can somebody help me?

**Comment by vickvasquez** [comment]
Check this alternative https://bit.ly/44Zsuij

**Comment by GeorgiKeranov** [comment]
> Hello.
> 
> I get this error: ERROR: Timed out waiting for the element with xpath "//span[@dir="auto"][text()="Used – Good"]" to load
> 
> Can somebody help me?

Check if is there any difference in the case of characters for example in facebook it may be "Used - good" instead of "Used - Good"
