### ISSUE TITLE
confirm delete button 

### ISSUE THREAD

**Issue by jsmtl81** [GeorgiKeranov/facebook-marketplace-bot#15]
i'm having an issue with the confirm delete button , is the selector changed ? 

this is what i have at this time 
# Click on confirm button to delete
	confirm_delete_selector = 'div[aria-label="Delete Listing"] div[aria-label="Delete"][tabindex="0"]'
	if scraper.find_element(confirm_delete_selector, False, 3):
		scraper.element_click(confirm_delete_selector)
	
	# Wait until the popup is closed
	scraper.element_wait_to_be_invisible('div[aria-label="Your Listing"]')

but it is not working for me

**Comment by GeorgiKeranov** [comment]
Fixed in c24ed7a6cfb8ce3c415440249059f6501acea28a

**Comment by jsmtl81** [comment]
Thank you very much Georgi 
it worked ..
Great work !
