### ISSUE TITLE
2# error deleting post

### ISSUE THREAD

**Issue by F-UwU-aaa** [GeorgiKeranov/facebook-marketplace-bot#16]
After having published, that is, when the publication is already done and I want to publish again, I get that

![codigo](https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/135071420/4864a9f7-41e6-4fe8-af29-0d2d968ce0d9)

![1error](https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/135071420/ad55282b-d338-4b13-baaf-37e33fc4494e)

and when i put again : python main.py    i get this error

![2codigo](https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/135071420/7c45c587-5633-4cdf-984c-ea5744451c0c)
![2error](https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/135071420/fc83ab50-73b1-48a4-ae6b-728651f15fa3)

and I don't know how to fix it please help me

**Comment by GeorgiKeranov** [comment]
Try to get the latest changes from this repository, this problem was fixed in the latest commit - https://github.com/GeorgiKeranov/facebook-marketplace-bot/commit/c24ed7a6cfb8ce3c415440249059f6501acea28a
