### ISSUE TITLE
posting on facebook not working because of the chrome version 

### ISSUE THREAD

**Issue by jsmtl81** [GeorgiKeranov/facebook-marketplace-bot#18]
Hello Georgi , 

i did what you mentioned in the previous issue but it was closed so i'm writting here.
my chrome got updated to v(ersion 117.0.5938.132 (Official Build) (64-bit))
i did what you mentioned before to specify the version to install 
chrome_driver_path = ChromeDriverManager("114.0.5735.16").install()
		self.driver = webdriver.Chrome(service=ChromeService(chrome_driver_path), options = self.driver_options)
but that didn't work because it doesn't match the chrome version i have , i need to get the right version and it is not available on https://chromedriver.chromium.org/downloads   .
the version 117.0.5938.132 is actually available on https://googlechromelabs.github.io/chrome-for-testing/

how can i let the script to download the right version 117.0.5938.132  i need ?

or 
can i downgrade chrome and use the old version and disable the updates because it keeps updating back when i did 

Thanks

**Comment by GeorgiKeranov** [comment]
Please try to not specify version like that:
```
chrome_driver_path = ChromeDriverManager().install()
```
