### ISSUE TITLE
chromedriver not found on Linux

### ISSUE THREAD

**Issue by f8vze** [GeorgiKeranov/facebook-marketplace-bot#2]
Hi Georgi!

Thank you for developing this! Some questions. I am using Linux.

First of all, best pre-use setup command I have thus far is this:
```
sudo apt-get install libgconf2-dev
pip3 install selenium pickle-mixin chromedriver
```

And that makes chromedriver work:
```
$ cd ~
$  ./.local/chromedriver-Linux64
Starting ChromeDriver 2.24.417424...
Only local connections are allowed.
```

However:

```
$ cd ~
$ export PATH="${PATH}:${PWD}/.local"
$ cd facebook-marketplace-bot
$ python3 main.py 
Traceback (most recent call last):
...
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
...
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
...
AttributeError: 'Scraper' object has no attribute 'driver'
```

**Comment by f8vze** [comment]
And, if I just use `python` instead of `python3` I get:
```
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from helpers.scraper import Scraper
  File "helpers/scraper.py", line 159
    print(f'ERROR: Timed out waiting for the element with css selector "{selector}" to load')
                                                                                           ^
SyntaxError: invalid syntax
```

**Comment by GeorgiKeranov** [comment]
Yes, sorry about that. I have forgotten to add in the README that you need Google Chrome installed and chromedriver in your PATH in order for this script to work.

1. Install the "Google Chrome" browser if you don't have it already in your Linux environment - https://www.google.com/chrome/.

2. Download the "chromedriver" based on the "Google Chrome" version from here - https://chromedriver.chromium.org/downloads.
3. After you have downloaded the "chromedriver.zip", you will have to unzip it.
4. Put the unzipped "chromedriver" file in the '/usr/bin/' directory to make it executable. First go to the directory where the "chromedriver" is and you can use these commands:
```
sudo mv chromedriver /usr/bin/chromedriver 
sudo chown root:root /usr/bin/chromedriver 
sudo chmod +x /usr/bin/chromedriver
```

**Comment by f8vze** [comment]
Thank you, but please do add it to the readme for others! Thank you!

**Comment by GeorgiKeranov** [comment]
I have added it to the readme. Also, I have added a new extra step from which you can hide your "chromedriver" from websites that check for bots. You can check it in the [readme](https://github.com/GeorgiKeranov/facebook-marketplace-bot/blob/master/README.md) in Installation -> step 7.
