### ISSUE TITLE
whenever i update the items.csv then i get error "File was not found in csvscsvs\items.csv"

### ISSUE THREAD

**Issue by bigdong69696** [GeorgiKeranov/facebook-marketplace-bot#21]
whenever i update the items.csv then i get error "File was not found in csvscsvs\items.csv"

**Comment by GeorgiKeranov** [comment]
It is trying to load a file inside a "csvscsvs\items.csv" directory I don't know why it is trying to do that you can check if helpers/csv_helper.py on line 7 is the same like that:
```
file_path = 'csvs' + os.path.sep + csv_file_name + '.csv'
```
If it is not, please change the line with the above code

**Comment by bigdong69696** [comment]
no it is opening the correct directory i was able to fix it by changing the encoding
