### ISSUE TITLE
Publish Button not press/ listing not post 

### ISSUE THREAD

**Issue by shahbazinayat** [GeorgiKeranov/facebook-marketplace-bot#22]
i have tried many time but at publish time bot stop and after that terminate. I also try different method but not

**Comment by GeorgiKeranov** [comment]
If the button is disabled, you won't be able to click it, it may have been disabled because of limit of ads per month

**Comment by shahbazinayat** [comment]
I have checked and there is no posting limit. If i do posting manually i can easily publish and but when used this tool it works but at publish time it's not worked and didn't press publish and publish button blue and i can press manually
