### ISSUE TITLE
Dropdownlist Model is not working 

### ISSUE THREAD

**Issue by jsmtl81** [GeorgiKeranov/facebook-marketplace-bot#23]
Hello Georgi ,

I recently have an issue , i realized that facebook put the Model field as text and sometimes he changed to dropdownlist .

now in my case the Model is dropdownlist and i have this code and it is not working to click and select the value of the model and the same code is working for Make or year . 

 # Scroll to make select
	scraper.scroll_to_element('label[aria-label="Make"]')
	# Expand make select
	scraper.element_click('label[aria-label="Make"]')
	scraper.element_click_by_xpath('//span[text()="' + data['Make'] + '"]')
    

	#scraper.element_send_keys('label[aria-label="Model"] input', data['Model'])
	
	scraper.scroll_to_element('label[aria-label="Model"]')
	# Expand model select
	scraper.element_click('label[aria-label="Model"]')
	scraper.element_click_by_xpath('//span[text()="' + data['Model'] + '"]')

	# Scroll to mileage input
	scraper.scroll_to_element('label[aria-label="Mileage"] input')	
	# Click on the mileage input
	scraper.element_send_keys('label[aria-label="Mileage"] input', data['Mileage'])

when the code execute , it start filling the year , make  and when it get to the model , i have to click on the model dropdown so the script can continue , so for some reason , it tries to click the model and unable to continue ,  can you help me with that please

**Comment by GeorgiKeranov** [comment]
Hey, you can check how I have implemented this on the Category dropdown - https://github.com/GeorgiKeranov/facebook-marketplace-bot/blob/master/helpers/listing_helper.py#L131-L141

I need more context for the item that you are trying to upload, please provide me with the CSV that is not working for you, if you need more detailed help!
