### ISSUE TITLE
Selector delete

### ISSUE THREAD

**Issue by F-UwU-aaa** [GeorgiKeranov/facebook-marketplace-bot#25]
# Click on confirm button to delete
	confirm_delete_selector = 'div[aria-label="Delete listing"] div[aria-label="Delete"][tabindex="0"]'
	if scraper.find_element(confirm_delete_selector, False, 3):
		scraper.element_click(confirm_delete_selector)
	else:
		confirm_delete_selector = 'div[aria-label="Delete Listing"] div[aria-label="Delete"][tabindex="0"]'
		if scraper.find_element(confirm_delete_selector, True, 3):
			scraper.element_click(confirm_delete_selector)
	
	

Hay veces en dónde si funciona y hay otra veces en dónde no funciona solo hace click en el icono de basudero y de hay ya no hace click en el botón azul de elimar creo actualizaron el código de facebook

**Comment by F-UwU-aaa** [comment]
Si no da siempre revise el HTML y coincide todo pero aún así no hace click en el de botón azul de borrar

**Comment by F-UwU-aaa** [comment]
Si funciona en algunas cuentas pero en otras no tienes mucha razón pero como se podría hacer para que funcione en todas las cuentas en general por que en algunas cuentas tiene el : confirm_delete_selector = 'div[aria-label="Delete listado"] div[ aria-label="Delete"][tabindex="0"]' y en otras no existe el : div[aria-label="Eliminar listado"]@GeorgiKeranov @jsmtl81 se cambia por una etiqueta asi aria-labelledby=":r45:" ayudaaa!!!!!!@GeorgiKeranov @jsmtl81

**Comment by GeorgiKeranov** [comment]
Please, type the issue in English if you want any help, I could not understand your language.
