### ISSUE TITLE
can someone please help with the delete post on marketplace ,

### ISSUE THREAD

**Issue by jsmtl81** [GeorgiKeranov/facebook-marketplace-bot#27]
hello everyone , I'm trying to solve the delete issue when it comes to reposting on marketplace but still not working for me  .
can someone help on that please , the current delete function is no longer working because facebook has a different HTML , and i also realised that they don't have the same xpath ID in each account for the delete button . 

please share anything you know Thanks 
@GeorgiKeranov

**Comment by GeorgiKeranov** [comment]
Please pull the latest changes, it is fixed in the last commit :)

**Comment by jsmtl81** [comment]
Thanks Georgi , your code actually worked but the only issue with this is that facebook has two delete box confirmation so sometimes it is square and another is rectangle . the code you just did works on the square one not on the rectangle . if you any comment or update please let me know . 
Thanks
