### ISSUE TITLE
Error on category selection

### ISSUE THREAD

**Issue by NikoTumi** [GeorgiKeranov/facebook-marketplace-bot#28]
I can't seem to get the script to get past the category selection part on the post.

I tried going through the categories and choosing the deepest category and pasted that into the csv file, but it didn't work. Not sure how to fix this. Any help would be appreciated. 

ERROR: Timed out waiting for the element with xpath "//span[text()="Hard Drive"]" to load

Thank you and best regards!

**Comment by GeorgiKeranov** [comment]
Please, check if the category is named exactly "Hard Drive", it may be "Hard drive" which causes the script to not find it

**Comment by NikoTumi** [comment]
Its not even getting to the point where it enters the string into the text field on the webpage. I'm on the east coast. Not sure if that has anything to do with it, but I saw somewhere that FB might have different layouts dependent on the region.

**Comment by NikoTumi** [comment]
Hi Georgi!
Just a follow up report. 
If I click through the top categories, once I get to the lower subcategory, the text field auto fills and script continues.
Strange thing is I can copy-paste csv category string and the script continues as well.
But the script does not go to the next page which inputs location and groups. I have to do that manually and the script continues to the publish page, which also must be done manually. Then the script errors out.
