### ISSUE TITLE
Unable to click on Span selector because it is inside a div and div will receives the click => throws an error.

### ISSUE THREAD

**Issue by amritium** [GeorgiKeranov/facebook-marketplace-bot#3]
Hey, first if all amazing code and I have parallelly trying to make your code. I am working with a real data and I can see this script throws alot of errors when is comes to clicking on elements. Most common one is unable to location selector error even element has successfully loaded on chrome screen. Can you please help? I can post screenshots and error codes if you like? thanks

**Comment by GeorgiKeranov** [comment]
I think that I have fixed the common problems with clicking on elements in the last commits. If you still have an error, please give me the error code, thank you!
