### ISSUE TITLE
Fails to go next page for location entry and publish

### ISSUE THREAD

**Issue by NikoTumi** [GeorgiKeranov/facebook-marketplace-bot#30]
Hello.
The script runs well up to before location entry. This is after the description is entered, there is a next button to go to next page for location and groups. The script fails to go to the next page, unless done so by the user. Once the user selects it, the script continues to input location and select groups (not tried groups, I keep it blank), but then fails to publish. Its left to the user to manually click the publish button. Once done, the script fails to enter a new iten on the next row of the item.csv.

I think it fails to publish due to a no entry for groups column. I'm thinking about going into the script and doing a if blank continue conditional statement.

**Comment by NikoTumi** [comment]
Also, sometimes I have to manually select top categories in order for the script to auto write in the sub category. But if I copy and paste what I have in the csv, the script continues.

**Comment by kb18951452** [comment]
> Also, sometimes I have to manually select top categories in order for the script to auto write in the sub category. But if I copy and paste what I have in the csv, the script continues.

@NikoTumi 
Please create a separate issue for this bug. Screenshots are really helpful, or a video, or a gif.

**Comment by NikoTumi** [comment]
Hi! Thanks for the follow up. Here is a link to desktop recording of the script running with shots of the csv file.

https://drive.google.com/file/d/1TQrL8dCKoVinFlsYQ5-2-asst3os2-4Z/view?usp=drive_link

Here is the first couple lines of the csv file:
[START]
Title,Photos Folder,Photos Names,Price,Category,Condition,Brand,Description,Location,Groups
Zoom R16 Audio Interface,F:\Pictures\For_Sale\,AudioInterface_01.jpg; AudioInterface_02.jpg,200,Studio Recording Equipment,Used - Like New,Zoom,"Zoom R16 Mixer/Recorder/Interface
Portable recorder, uses 6 AA batteriesor power supply. Has 2 built in condensor mics.
Record 16 tracks as a standalon recorder.

Or use as an audio interface. Outputs 8 channels.",Saint Petersburg Florida,"St. Petersburg Fl. Online Yard Sale; St. Petersburg & Surrounding Areas : Buy, Bargain, Give, Sell, and Swap; St Petersburg garage sale; "
Light up Cornhole,F:\Pictures\For_Sale\,cornhole_01.jpg,20,Cornhole Bag Toss,Used - Like New,,"Foldable cornhole game that lights ups, and the bean bags light up too.",Saint Petersburg Florida,"St. Petersburg Fl. Online Yard Sale; St. Petersburg & Surrounding Areas : Buy, Bargain, Give, Sell, and Swap; St Petersburg garage sale; "
[END]
Thanks for the help!

**Comment by GeorgiKeranov** [comment]
For now we don't support sub categories, but in future I may add it, thanks for the suggestion!
