### ISSUE TITLE
Hangs on Wheel of Death / Greyed Out 'Publish' Button

### ISSUE THREAD

**Issue by benrede** [GeorgiKeranov/facebook-marketplace-bot#34]
ERROR: Timed out waiting for the element with xpath "//span[text()=""]" to load

- No matter what I do to alter the code this error is always thrown on the final 'Publish' page. Unsure how to resolve.

![Screenshot 2024-02-23 085330](https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/161009367/25550cbe-4bec-4d8d-a636-78feef8f90fa)

![Screenshot 2024-02-23 160212](https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/161009367/e3a76ada-2576-4f71-b3d8-6acb111d09c1)

**Comment by Dhruv-Sahu** [comment]
add any of the grp name in the csv file ! example: under the group table coloumn type: "Buy and Sell Anything Perth".
the name should be precise and exact. Unfortunately without the group name the code wont progress further.

**Comment by benrede** [comment]
> add any of the grp name in the csv file ! example: under the group table coloumn type: "Buy and Sell Anything Perth". the name should be precise and exact. Unfortunately without the group name the code wont progress further.

I've tried this and unfortunately still didn't work. Although after many tweaks and revisions to the code I receive the following error instead: 
![Screenshot 2024-04-23 112619](https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/161009367/b82ef792-53ed-47df-b250-ddcb3d430b68)

**Comment by GeorgiKeranov** [comment]
I think that I fixed the problem with the last commit, try in your terminal where the project is:
`git pull` and run the script again

**Comment by benrede** [comment]
Thanks Georgi. Unfortunately getting the following error:
![image](https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/161009367/135b16e1-5100-4f24-b288-93097f35d2a0)
