### ISSUE TITLE
More than 1 line in the description causes error

### ISSUE THREAD

**Issue by NikoTumi** [GeorgiKeranov/facebook-marketplace-bot#35]
Hi again. 
This something I noticed and have to later paste the description. If there is a multiline description, the program erros. Does not run all the way through, but if I cut out, it runs (minus the other issues I posted)

Data:
Title,Photos Folder,Photos Names,Price,Category,Condition,Brand,Description,Location,Groups
Gaming PC and Monitor ,F:\Pictures\For_Sale\,PC_01.jpg; PC_02.jpg; PC_03.jpg; PC_04.jpg; PC_05.jpg; PC_06.jpg; PC_07.jpg; PC_08.jpg; PC_09.jpg; PC_10.jpg,460,Desktop Computers,Used - Like New,,"This is a great price for what your getting.

PCVR Demo
https://drive.google.com/file/d/1cQUhGEOuKnpRK67qvB_0XhQjl_RgjNjq/view?usp=drive_link

Performance Demo
https://drive.google.com/file/d/1YKHnopN3JIqAYhC6txLuTFSLl_0hA5pq/view?usp=drive_link

1.	Highly capable gaming PC $460 for everything
1.1.	CPU Intel 6600k - 4 Core $100
1.2.	GPU Radeon RX 580 $200
1.3.	Wi-Fi 6 $40
1.4.	16 Gb RAM $40
1.5.	500 Gb HD $20
1.6.	Fan Heatsink CPU Cooler $20
1.7.	Mother Board $100
1.8.	Custom PC Case $40
1.9.	Wired Gaming Mouse with Number pad $40
1.10.	Keyboard $0
2.	144 Hz 24” Gaming Monitor $60
3. 	SteelSeries Arctic 5 Headphones - 7.1 Surround sound with Mic $60","Saint Petersburg, Florida","St. Petersburg Fl. Online Yard Sale; St. Petersburg & Surrounding Areas : Buy, Bargain, Give, Sell, and Swap; St Petersburg garage sale; "

**Comment by GeorgiKeranov** [comment]
You need to format the csv file with quotes, check out the latest format from here - https://github.com/GeorgiKeranov/facebook-marketplace-bot/blob/master/csvs/items.csv
