### ISSUE TITLE
Fails to choose catagory

### ISSUE THREAD

**Issue by NikoTumi** [GeorgiKeranov/facebook-marketplace-bot#36]
Before I put in a category, I search for it first and copy paste into the items.csv
But I still get errors for these subcategories. If select drums form the categorizes, it autofill's from there. I think there needs to be a "Drums, Acoustic Drums

ERROR: Timed out waiting for the element with xpath "//span[text()="Acoustic Drums"]" to load
Traceback (most recent call last):

Console error output:

  File ~\Documents\GitHub\facebook-marketplace-bot\helpers\listing_helper.py:13 in update_listings
    publish_listing(listing, type, scraper)

  File ~\Documents\GitHub\facebook-marketplace-bot\helpers\listing_helper.py:55 in publish_listing
    globals()[function_name](data, scraper)

  File ~\Documents\GitHub\facebook-marketplace-bot\helpers\listing_helper.py:136 in add_fields_for_item
    scraper.element_click_by_xpath('//span[text()="' + data['Category'] + '"]')

  File ~\Documents\GitHub\facebook-marketplace-bot\helpers\scraper.py:204 in element_click_by_xpath
    element = self.find_element_by_xpath(xpath)

  File ~\Documents\GitHub\facebook-marketplace-bot\helpers\scraper.py:181 in find_element_by_xpath
    exit()

NameError: name 'exit' is not defined

DATA:
Title,Photos Folder,Photos Names,Price,Category,Condition,Brand,Description,Location,Groups
Zildjian ZBT Symbols,F:\Pictures\For_Sale\,Symbols_01.jpg; Symbols_02.jpg; Symbols_04.jpg; Symbols_05.jpg; Symbols_06.jpg; Symbols_07.jpg,160,Acoustic Drums,Used - Fair,Zildjian,"Symbols for $100 together (1 & 2)
1. Zildjian ZBT 14 Hi Hat Drum Cymbals $60 
2. Zildjian ZBT 18 Crash Drum Cymbal $60 
3.SOLD Zildjian ZBT 15 Ride Drum Cymbal $60 SOLD","Saint Petersburg, Florida","St. Petersburg Fl. Online Yard Sale; St. Petersburg & Surrounding Areas : Buy, Bargain, Give, Sell, and Swap; St Petersburg garage sale; "

**Comment by GeorgiKeranov** [comment]
First of all check the latest format for the csv, we are using quotes - https://github.com/GeorgiKeranov/facebook-marketplace-bot/blob/master/csvs/items.csv

When you fix the formating, just add "Drums, " before the "Acoustic Drums" and it will be fixed.
