### ISSUE TITLE
Shows Query Error after hitting publish

### ISSUE THREAD

**Issue by Dhruv-Sahu** [GeorgiKeranov/facebook-marketplace-bot#38]
The terminal error during this part is :
ERROR: Timed out waiting for the element with css selector "div[aria-label="Marketplace sidebar"] a[aria-label="Create new listing"]" to load.

And the image on facebook marketplace is : 
![WhatsApp Image 2024-04-22 at 9 37 04 PM](https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/82047955/0a859625-84da-421c-8f02-3ad7e254bd72)

Do give a work around or method to make this work.

**Comment by GeorgiKeranov** [comment]
I think that I fixed the problem with the last commit, try in your terminal where the project is:
`git pull` and run the script again
