### ISSUE TITLE
After getting into Marketplace tab bot stops

### ISSUE THREAD

**Issue by Kopa2005** [GeorgiKeranov/facebook-marketplace-bot#4]
Hey I think Facebook changed the layout so the bot stopped working. After it gets to this url it spits out an error

https://www.facebook.com/marketplace/create

I think the label name changed or something :)

**Comment by gregory-carlton** [comment]
Same as myself. @GeorgiKeranov has updated the repo 18 days ago. Are you seeing this @GeorgiKeranov ?

**Comment by GeorgiKeranov** [comment]
I have no problems with it. Please give me the error that you are receiving and the way you use it in order to reproduce the problem and fix it.

**Comment by GeorgiKeranov** [comment]
I have found the issue and fixed it in 82247a5b7ee6c9c8975cd3092bfcd3712fa8f485
