### ISSUE TITLE
Need to include location by zip code ?

### ISSUE THREAD

**Issue by clubreseau** [GeorgiKeranov/facebook-marketplace-bot#5]
Need to include location by zip code ?

how >

**Comment by GeorgiKeranov** [comment]
Good idea, I am thinking of adding location and zip code in the future!

**Comment by GeorgiKeranov** [comment]
I have added an option to write a location in the CSV file, you can see how you can do it from here - https://github.com/GeorgiKeranov/facebook-marketplace-bot/blob/master/csvs/items.csv
https://github.com/GeorgiKeranov/facebook-marketplace-bot/blob/master/csvs/vehicles.csv
