### ISSUE TITLE
Got Error "KeyError: 'Description'"

### ISSUE THREAD

**Issue by agusgithub123** [GeorgiKeranov/facebook-marketplace-bot#6]
Thanks for your script mate, but i got an error like this, can you help to fix it ?

====== WebDriver manager ======
Current google-chrome version is 106.0.5249
Get LATEST chromedriver version for 106.0.5249 google-chrome
Driver [C:\Users\Admin\.wdm\drivers\chromedriver\win32\106.0.5249.61\chromedriver.exe] found in cache
Traceback (most recent call last):
  File "C:\VsCode\facebook-marketplace-bot-master (1)\facebook-marketplace-bot-master\main.py", line 24, in <module>
    update_listings(item_listings, 'item', scraper)
  File "C:\VsCode\facebook-marketplace-bot-master (1)\facebook-marketplace-bot-master\helpers\listing_helper.py", line 13, in update_listings
    publish_listing(listing, type, scraper)
  File "C:\VsCode\facebook-marketplace-bot-master (1)\facebook-marketplace-bot-master\helpers\listing_helper.py", line 61, in publish_listing
    scraper.element_send_keys('label[aria-label="Description"] textarea', data['Description'])
KeyError: 'Description'

**Comment by agusgithub123** [comment]
i also try to delete description script to see the next step of the script then i got another error like this ;
====== WebDriver manager ======
Current google-chrome version is 106.0.5249
Get LATEST chromedriver version for 106.0.5249 google-chrome
Driver [C:\Users\Admin\.wdm\drivers\chromedriver\win32\106.0.5249.61\chromedriver.exe] found in cache
ERROR: Timed out waiting for the element with xpath "//span[text()=""]" to load

**Comment by EduarDG09** [comment]
In the csv the column title for the description is 'Description ' with an extra space at the end, so when the code tries to find 'Description' it fails.

**Comment by EduarDG09** [comment]
> i also try to delete description script to see the next step of the script then i got another error like this ; ====== WebDriver manager ====== Current google-chrome version is 106.0.5249 Get LATEST chromedriver version for 106.0.5249 google-chrome Driver [C:\Users\Admin.wdm\drivers\chromedriver\win32\106.0.5249.61\chromedriver.exe] found in cache ERROR: Timed out waiting for the element with xpath "//span[text()=""]" to load

I think this is because your group list is empty :p

**Comment by GeorgiKeranov** [comment]
@EduarDG09 was right, there was white space in the `Description` column in the `csvs/items.csv`. @agusgithub123 you can fix it by removing the white space at the end of the column. I have fixed it for future users - 4244e325b1f433ec296ea964762798b9f1a7ccbe.

Thank you @EduarDG09!

**Comment by Jhoel-chipana-paye-FIRU** [comment]
tuve el mismo error pero con  KeyError: 'Title' y lei los comentarios de este mismo problema pero aun no puedo arreglar y nose como solucionar me sale asi 
![Captura](https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/135071420/9c1a1227-ce18-4ef6-bb7f-f5a5f68e3081)
y m archivo .cvs esta asi 
![Captura PNG2](https://github.com/GeorgiKeranov/facebook-marketplace-bot/assets/135071420/474fc3ee-8e52-446c-a309-79700bc7f99b)
me pueden ayudar x favor

**Comment by Jhoel-chipana-paye-FIRU** [comment]
espero su respuesta pronto gracias :3
