### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by Kypso** [GeorgiKeranov/facebook-marketplace-bot#8]
When I open main.py, google chrome opens and the facebook login page opens and logs in to the account and then nothing happens in the shell, nothing is displayed
![obraz_2022-10-31_163926360](https://user-images.githubusercontent.com/87091789/199048376-fbcc3e19-8aca-4acf-8d57-389b57896189.png)

**Comment by Kypso** [comment]
i tried on virtual machine and same problem

**Comment by Kypso** [comment]
after 5 minutes something like this appeared to me
![image](https://user-images.githubusercontent.com/87091789/199049928-7305a088-de56-4714-a359-feb1e355d476.png)

**Comment by GeorgiKeranov** [comment]
For the first time that you run main.py, you have to login manually in the browser.

**Comment by Kypso** [comment]
I am logged in but when I run main.py the program tells me to log in again

pon., 31 paź 2022 o 17:06 Georgi Keranov ***@***.***>
napisał(a):

**Comment by Kypso** [comment]
![image](https://user-images.githubusercontent.com/87091789/199056572-f278505b-5743-4fe0-8528-dd48e25c188f.png)

**Comment by Kypso** [comment]
https://user-images.githubusercontent.com/87091789/199059925-2d23d538-9d0e-4f71-b104-1ed2bcda0657.mp4

**Comment by agusgithub123** [comment]
Try to change language on your account into english (US) mate. . .

**Comment by Kypso** [comment]
Thanks, helped, could you please tell me how to disable it so that it doesn't delete ads with the same title so that it leaves

**Comment by agusgithub123** [comment]
It is to follow facebook rules. You cannot post in same title. It will detect duplicate so it will againts the rules.

**Comment by agusgithub123** [comment]
I am stuck in publishing ads, is yours running well ?

**Comment by Kypso** [comment]
i have 1500 post with te same title only photo must be diffrent

**Comment by Kypso** [comment]
> I am stuck in publishing ads, is yours running well ?

yes

**Comment by Kypso** [comment]
Okay, I managed to do it so that it does not remove, but still needs to add a city column

**Comment by agusgithub123** [comment]
> > I am stuck in publishing ads, is yours running well ?
> 
> yes

I still got this error at the end step of publishing ads...
===== WebDriver manager ======
Current google-chrome version is 106.0.5249
Get LATEST chromedriver version for 106.0.5249 google-chrome
Driver [C:\Users\Admin.wdm\drivers\chromedriver\win32\106.0.5249.61\chromedriver.exe] found in cache
ERROR: Timed out waiting for the element with css selector "input[placeholder="Search your listings"]" to load

**Comment by agusgithub123** [comment]
> Okay, I managed to do it so that it does not remove, but still needs to add a city column

Just wait the next update, i hope all column can be fill

**Comment by GeorgiKeranov** [comment]
I have added an column to write a location in the CSV file, you can see how you can do it from here - https://github.com/GeorgiKeranov/facebook-marketplace-bot/blob/master/csvs/items.csv
https://github.com/GeorgiKeranov/facebook-marketplace-bot/blob/master/csvs/vehicles.csv
