### ISSUE TITLE
Great Script

### ISSUE THREAD

**Issue by agusgithub123** [GeorgiKeranov/facebook-marketplace-bot#9]
Can you please create script to fill all this column when you have free time ?
![image](https://user-images.githubusercontent.com/67958650/199792100-3d99b63e-16f9-4216-98a3-e9a061f116b9.png)

Thanks mate !

**Comment by GeorgiKeranov** [comment]
Yes, I have added a column for Location in the new update, you can see how you can do it from here - https://github.com/GeorgiKeranov/facebook-marketplace-bot/blob/master/csvs/items.csv
https://github.com/GeorgiKeranov/facebook-marketplace-bot/blob/master/csvs/vehicles.csv
